# Generated by Django 6.1.1 on 2026-09-08 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('examinations', '0001_initial'),
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='General', max_length=50)),
            ],
            options={
                'db_table': 'permission_codes',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('LOCK', 'Lock'), ('UNLOCK', 'Unlock'), ('GRANT', 'Grant Permission'), ('REVOKE', 'Revoke Permission'), ('WARN', 'Warning'), ('SUSPEND', 'Suspend'), ('ARCHIVE', 'Archive'), ('NOTIFY', 'Notification Sent')], max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('ASSIGNMENT', 'New Assignment'), ('APPROVAL', 'Request Approved'), ('REJECTION', 'Request Rejected'), ('WARNING', 'Warning Issued'), ('SUSPENSION', 'Suspension'), ('MARK_EDIT', 'Mark Edit Approved'), ('REPORT', 'Report Status Change'), ('SYSTEM', 'System Message'), ('REMINDER', 'Reminder')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('related_object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermissionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.academicyear')),
                ('examination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='examinations.examination')),
                ('grade_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.gradelevel')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_assignments', to='core.userprofile')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.stream')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.subject')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.term')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.permissioncode')),
            ],
            options={
                'db_table': 'permission_assignments',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='SuspensionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_suspensions', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_suspensions', to=settings.AUTH_USER_MODEL)),
                ('teacher_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', to='core.userprofile')),
            ],
            options={
                'db_table': 'suspension_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_warnings', to=settings.AUTH_USER_MODEL)),
                ('teacher_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='core.userprofile')),
            ],
            options={
                'db_table': 'warning_records',
                'ordering': ['-issued_at'],
            },
        ),
    ]
