# Generated by Django 6.1.1 on 2026-09-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='tsc_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
