# Generated by Django 6.1.1 on 2026-09-08 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('teachers', '0002_teacherprofile_tsc_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherassignment',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.term'),
        ),
        migrations.CreateModel(
            name='ClassTeacherRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('ADD_LEARNER', 'Add learners to class'), ('TRANSFER_LEARNER', 'Transfer learners'), ('ENTER_MARKS', 'Enter marks'), ('EDIT_MARKS', 'Edit marks'), ('SCHOOL_WIDE_MARKS', 'School-wide mark entry'), ('GENERATE_REPORT', 'Generate reports'), ('VIEW_ANALYTICS', 'View analytics'), ('OTHER', 'Other (specify)')], max_length=30)),
                ('specific_students', models.TextField(blank=True, help_text='Comma-separated admission numbers (if requesting access to specific learners only).')),
                ('reason', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_days', models.IntegerField(default=7, help_text='How long the granted permission should last (in days).')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.academicyear')),
                ('grade_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.gradelevel')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_class_teacher_requests', to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.stream')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_requests', to='teachers.teacherprofile')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.term')),
            ],
            options={
                'db_table': 'class_teacher_requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
