# Generated by Django 6.1.1 on 2026-09-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_add_permissions_notifications_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='created_via',
            field=models.CharField(choices=[('SELF_REGISTER', 'Self-Registered'), ('MANUAL', 'Manually Added')], default='SELF_REGISTER', max_length=20),
        ),
    ]
