# Generated by Django 5.2.17 on 2026-09-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0004_add_created_via"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherrequest",
            name="role",
            field=models.CharField(
                choices=[("teacher", "Teacher"), ("class_teacher", "Class Teacher")],
                default="teacher",
                max_length=20,
            ),
        ),
    ]
