# Generated by Django 6.1.1 on 2026-09-08 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examinations', '0001_initial'),
        ('school', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('curriculum', models.CharField(choices=[('844', '8-4-4 / KCSE'), ('CBC', 'CBC / CBA')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.academicyear')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grade_levels', models.ManyToManyField(blank=True, related_name='assessment_schemes', to='school.gradelevel')),
            ],
            options={
                'db_table': 'assessment_schemes',
                'ordering': ['curriculum', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('SBA', 'School-Based Assessment'), ('SUMMATIVE', 'Summative Assessment'), ('PROJECT', 'Project'), ('EXAMINATION', 'Examination'), ('PRACTICAL', 'Practical'), ('OTHER', 'Other')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='grading.assessmentscheme')),
            ],
            options={
                'db_table': 'assessment_components',
            },
        ),
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('FORMATIVE', 'Formative Assessment'), ('SUMMATIVE', 'Summative Assessment'), ('SBA', 'School-Based Assessment'), ('KJSEA', 'KJSEA Assessment')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbc_assessment_types', to='grading.assessmentscheme')),
            ],
            options={
                'db_table': 'cbc_assessment_types',
            },
        ),
        migrations.CreateModel(
            name='ComponentAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aggregation_type', models.CharField(choices=[('WEIGHTED', 'Weighted Average'), ('SUM', 'Sum of Scores'), ('CUSTOM', 'Custom Formula')], default='WEIGHTED', max_length=20)),
                ('formula', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('components', models.ManyToManyField(related_name='aggregations', to='grading.assessmentcomponent')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregations', to='grading.assessmentscheme')),
            ],
            options={
                'db_table': 'component_aggregations',
            },
        ),
        migrations.CreateModel(
            name='KCSEGradeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_scope', models.CharField(choices=[('ALL', 'All Subjects'), ('SPECIFIC', 'Specific Subject')], default='ALL', max_length=20)),
                ('grade', models.CharField(max_length=3)),
                ('grade_name', models.CharField(max_length=50)),
                ('points', models.DecimalField(decimal_places=1, max_digits=3)),
                ('min_score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('descriptor', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kcse_rules', to='grading.assessmentscheme')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.subject')),
            ],
            options={
                'db_table': 'kcse_grade_rules',
                'ordering': ['scheme', 'order', 'min_score'],
            },
        ),
        migrations.CreateModel(
            name='KCSEOverallCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calculation_type', models.CharField(choices=[('STANDARD', 'Standard - Best 5 + Core Subjects'), ('CUSTOM', 'Custom Configuration')], default='STANDARD', max_length=20)),
                ('best_subject_count', models.IntegerField(default=5)),
                ('min_subjects', models.IntegerField(default=7)),
                ('max_subjects', models.IntegerField(default=9)),
                ('grade_boundaries', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('core_subjects', models.ManyToManyField(blank=True, related_name='kcse_core', to='school.subject')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kcse_calculations', to='grading.assessmentscheme')),
            ],
            options={
                'db_table': 'kcse_overall_calculations',
            },
        ),
        migrations.CreateModel(
            name='PerformanceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_code', models.CharField(choices=[('PL4', 'Exceeding Expectations'), ('PL3', 'Meeting Expectations'), ('PL2', 'Approaching Expectations'), ('PL1', 'Below Expectations')], max_length=3)),
                ('level_name', models.CharField(max_length=50)),
                ('descriptor', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('numeric_value', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbc_levels', to='grading.assessmentscheme')),
            ],
            options={
                'db_table': 'performance_levels',
                'ordering': ['scheme', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assessment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grading.assessmenttype')),
                ('grade_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.gradelevel')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbc_rubrics', to='grading.assessmentscheme')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.subject')),
            ],
            options={
                'db_table': 'cbc_rubrics',
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('max_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grading.performancelevel')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='grading.rubric')),
            ],
            options={
                'db_table': 'cbc_rubric_criteria',
                'ordering': ['rubric', 'order'],
            },
        ),
        migrations.CreateModel(
            name='RubricDescriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.TextField()),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptors', to='grading.rubriccriterion')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.performancelevel')),
            ],
            options={
                'db_table': 'cbc_rubric_descriptors',
                'unique_together': {('criterion', 'level')},
            },
        ),
        migrations.CreateModel(
            name='StudentCBAAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_results', models.JSONField(default=dict)),
                ('teacher_notes', models.TextField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grading.assessmentcomponent')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbc_assessments', to='examinations.examination')),
                ('overall_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cbc_results', to='grading.performancelevel')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.rubric')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbc_assessments', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
            ],
            options={
                'db_table': 'student_cbc_assessments',
                'unique_together': {('student', 'examination', 'rubric')},
            },
        ),
        migrations.CreateModel(
            name='StudentKCSEGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_mark', models.DecimalField(decimal_places=1, max_digits=5)),
                ('grade', models.CharField(max_length=3)),
                ('points', models.DecimalField(decimal_places=1, max_digits=3)),
                ('is_core', models.BooleanField(default=False)),
                ('is_best_subject', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kcse_grades', to='examinations.examination')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kcse_grades', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
            ],
            options={
                'db_table': 'student_kcse_grades',
                'unique_together': {('student', 'examination', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='StudentOverallCBA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_scores', models.JSONField(default=dict)),
                ('total_score', models.DecimalField(decimal_places=1, max_digits=5)),
                ('total_weighted_score', models.DecimalField(decimal_places=1, max_digits=5)),
                ('grade_equivalent', models.CharField(blank=True, max_length=3, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overall_cba', to='examinations.examination')),
                ('overall_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grading.performancelevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overall_cba', to='students.student')),
            ],
            options={
                'db_table': 'student_overall_cba',
                'unique_together': {('student', 'examination')},
            },
        ),
        migrations.CreateModel(
            name='StudentOverallKCSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.DecimalField(decimal_places=1, max_digits=5)),
                ('mean_grade', models.CharField(max_length=3)),
                ('mean_score', models.DecimalField(decimal_places=1, max_digits=5)),
                ('core_subjects_count', models.IntegerField(default=0)),
                ('best_subjects_count', models.IntegerField(default=0)),
                ('total_subjects_used', models.IntegerField(default=0)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overall_kcse', to='examinations.examination')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overall_kcse', to='students.student')),
            ],
            options={
                'db_table': 'student_overall_kcse',
                'unique_together': {('student', 'examination')},
            },
        ),
    ]
