# Generated by Django 6.1.1 on 2026-09-08 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('exam_type', models.CharField(choices=[('MID_TERM', 'Mid-Term'), ('END_TERM', 'End of Term'), ('MOCK', 'Mock Examination'), ('FINAL', 'Final Examination'), ('CAT', 'Continuous Assessment Test'), ('ASSIGNMENT', 'Assignment'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('results_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('LOCKED', 'Locked'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('max_score', models.IntegerField(default=100)),
                ('pass_mark', models.IntegerField(default=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicyear')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_examinations', to=settings.AUTH_USER_MODEL)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.curriculum')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.gradelevel')),
                ('subjects', models.ManyToManyField(related_name='examinations', to='school.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.term')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_examinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'examinations',
                'ordering': ['-academic_year', '-start_date'],
                'unique_together': {('academic_year', 'term', 'grade_level', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ExaminationClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_classes', to='examinations.examination')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.gradelevel')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.stream')),
            ],
            options={
                'db_table': 'examination_classes',
                'unique_together': {('examination', 'grade_level', 'stream')},
            },
        ),
        migrations.CreateModel(
            name='SubjectScoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.IntegerField(default=100)),
                ('min_score', models.IntegerField(default=0)),
                ('pass_mark', models.IntegerField(default=40)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_configs', to='examinations.examination')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
            ],
            options={
                'db_table': 'subject_score_configs',
                'unique_together': {('examination', 'subject')},
            },
        ),
    ]
